repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: master
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
